import { createAsyncThunk, createSlice, PayloadAction } from '@reduxjs/toolkit';
import { RootState } from '../../app/store';
import { DEFAULT_CITY } from '../../constants';
import { fetchCurrentWeather } from './weatherAPI';

interface WeatherData {
  description?: string;
  temp?: number;
}

export interface WeatherState {
  city: string;
  value?: WeatherData;
  status: 'idle' | 'loading' | 'failed';
}

const initialState: WeatherState = {
  city: DEFAULT_CITY,
  status: 'idle',
};

export const getCurrentWeatherAsync = createAsyncThunk(
  'weather/fetchCurrentWeather',
  async (city: string) => {
    const response = await fetchCurrentWeather(city);
    return response;
  }
);

export const weatherSlice = createSlice({
  name: 'weather',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    setWeather: (state, action: PayloadAction<{}>) => {
      state.value = action.payload;
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(getCurrentWeatherAsync.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(getCurrentWeatherAsync.fulfilled, (state, action) => {
        state.status = 'idle';

        const data = action.payload.data[0];

        const { temp, weather } = data;
        const { description } = weather;

        state.value = { description, temp };
      });
  },
});

export const { setWeather } = weatherSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.weather.value)`
export const selectCity = (state: RootState) => state.weather.city;
export const selectWeather = (state: RootState) => state.weather.value;

// TODO: possibly use hand-written async thunk
// We can also write thunks by hand, which may contain both sync and async logic.
// Here's an example of conditionally dispatching actions based on current state.
// export const incrementIfOdd =
//   (amount: number): AppThunk =>
//   (dispatch, getState) => {
//     const currentValue = selectCount(getState());
//     if (currentValue % 2 === 1) {
//       dispatch(incrementByAmount(amount));
//     }
//   };

export default weatherSlice.reducer;
